// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MHGD_detect_accel_MHGD_detect_accel,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=8924,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=22257,HLS_SYN_LUT=26776,HLS_VERSION=2024_2}" *)

module MHGD_detect_accel (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        Nt,
        Nr,
        mu,
        sigma2,
        mmse_init,
        lr_approx,
        iter,
        ap_return,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] Nt;
input  [31:0] Nr;
input  [31:0] mu;
input  [31:0] sigma2;
input  [31:0] mmse_init;
input  [31:0] lr_approx;
input  [31:0] iter;
output  [31:0] ap_return;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] x_hat;
wire   [63:0] H;
wire   [63:0] y;
wire   [63:0] v_tb;
reg   [31:0] iter_read_reg_159;
reg   [31:0] mu_read_reg_164;
reg   [31:0] Nt_read_reg_169;
reg   [63:0] x_hat_read_reg_176;
wire   [0:0] icmp_ln440_fu_142_p2;
reg   [0:0] icmp_ln440_reg_181;
wire   [0:0] icmp_ln455_fu_148_p2;
reg   [0:0] icmp_ln455_reg_185;
wire   [0:0] icmp_ln323_fu_154_p2;
reg   [0:0] icmp_ln323_reg_189;
wire    ap_CS_fsm_state2;
wire    grp_map_4_fu_124_ap_start;
wire    grp_map_4_fu_124_ap_done;
wire    grp_map_4_fu_124_ap_idle;
wire    grp_map_4_fu_124_ap_ready;
wire    grp_map_4_fu_124_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_map_4_fu_124_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_map_4_fu_124_m_axi_gmem_0_AWID;
wire   [31:0] grp_map_4_fu_124_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_map_4_fu_124_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_map_4_fu_124_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_map_4_fu_124_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_map_4_fu_124_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_map_4_fu_124_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_map_4_fu_124_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_map_4_fu_124_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_map_4_fu_124_m_axi_gmem_0_AWUSER;
wire    grp_map_4_fu_124_m_axi_gmem_0_WVALID;
wire   [127:0] grp_map_4_fu_124_m_axi_gmem_0_WDATA;
wire   [15:0] grp_map_4_fu_124_m_axi_gmem_0_WSTRB;
wire    grp_map_4_fu_124_m_axi_gmem_0_WLAST;
wire   [0:0] grp_map_4_fu_124_m_axi_gmem_0_WID;
wire   [0:0] grp_map_4_fu_124_m_axi_gmem_0_WUSER;
wire    grp_map_4_fu_124_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_map_4_fu_124_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_map_4_fu_124_m_axi_gmem_0_ARID;
wire   [31:0] grp_map_4_fu_124_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_map_4_fu_124_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_map_4_fu_124_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_map_4_fu_124_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_map_4_fu_124_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_map_4_fu_124_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_map_4_fu_124_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_map_4_fu_124_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_map_4_fu_124_m_axi_gmem_0_ARUSER;
wire    grp_map_4_fu_124_m_axi_gmem_0_RREADY;
wire    grp_map_4_fu_124_m_axi_gmem_0_BREADY;
wire    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start;
wire    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_done;
wire    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_idle;
wire    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_ready;
wire   [0:0] grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [127:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg    grp_map_4_fu_124_ap_start_reg;
reg    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
wire    ap_CS_fsm_state3;
reg    ap_predicate_op48_call_state3;
reg    ap_block_state3_on_subcall_done;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_map_4_fu_124_ap_start_reg = 1'b0;
#0 grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start_reg = 1'b0;
end

MHGD_detect_accel_map_4 grp_map_4_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_map_4_fu_124_ap_start),
    .ap_done(grp_map_4_fu_124_ap_done),
    .ap_idle(grp_map_4_fu_124_ap_idle),
    .ap_ready(grp_map_4_fu_124_ap_ready),
    .mu(mu_read_reg_164),
    .Nt(Nt_read_reg_169),
    .m_axi_gmem_0_AWVALID(grp_map_4_fu_124_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_map_4_fu_124_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_map_4_fu_124_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_map_4_fu_124_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_map_4_fu_124_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_map_4_fu_124_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_map_4_fu_124_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_map_4_fu_124_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_map_4_fu_124_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_map_4_fu_124_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_map_4_fu_124_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_map_4_fu_124_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_map_4_fu_124_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_map_4_fu_124_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_map_4_fu_124_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_map_4_fu_124_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_map_4_fu_124_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_map_4_fu_124_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_map_4_fu_124_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_map_4_fu_124_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_map_4_fu_124_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_map_4_fu_124_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_map_4_fu_124_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_map_4_fu_124_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_map_4_fu_124_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_map_4_fu_124_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_map_4_fu_124_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_map_4_fu_124_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_map_4_fu_124_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_map_4_fu_124_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_map_4_fu_124_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_map_4_fu_124_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .x_hat(x_hat_read_reg_176)
);

MHGD_detect_accel_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3 grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start),
    .ap_done(grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_done),
    .ap_idle(grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_idle),
    .ap_ready(grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_ready),
    .iter(iter_read_reg_159),
    .Nt(Nt_read_reg_169),
    .ap_return(grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return)
);

MHGD_detect_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_hat(x_hat),
    .H(H),
    .y(y),
    .v_tb(v_tb)
);

MHGD_detect_accel_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(grp_map_4_fu_124_m_axi_gmem_0_ARADDR),
    .I_CH0_ARLEN(grp_map_4_fu_124_m_axi_gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(grp_map_4_fu_124_m_axi_gmem_0_AWADDR),
    .I_CH0_AWLEN(grp_map_4_fu_124_m_axi_gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(grp_map_4_fu_124_m_axi_gmem_0_WDATA),
    .I_CH0_WSTRB(grp_map_4_fu_124_m_axi_gmem_0_WSTRB),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln455_reg_185 == 1'd1) | (icmp_ln440_reg_181 == 1'd0)))) begin
            grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_ready == 1'b1)) begin
            grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_map_4_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln440_fu_142_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_map_4_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_map_4_fu_124_ap_ready == 1'b1)) begin
            grp_map_4_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Nt_read_reg_169 <= Nt;
        icmp_ln440_reg_181 <= icmp_ln440_fu_142_p2;
        icmp_ln455_reg_185 <= icmp_ln455_fu_148_p2;
        iter_read_reg_159 <= iter;
        mu_read_reg_164 <= mu;
        x_hat_read_reg_176 <= x_hat;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln323_reg_189 <= icmp_ln323_fu_154_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3) & (((icmp_ln455_reg_185 == 1'd1) & (icmp_ln440_reg_181 == 1'd1) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return == 1'd1)) | ((icmp_ln440_reg_181 == 1'd0) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return == 1'd1) & (icmp_ln323_reg_189 == 1'd0))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3) & (((icmp_ln455_reg_185 == 1'd1) & (icmp_ln440_reg_181 == 1'd1) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return == 1'd1)) | ((icmp_ln440_reg_181 == 1'd0) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return == 1'd1) & (icmp_ln323_reg_189 == 1'd0))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_ARVALID = grp_map_4_fu_124_m_axi_gmem_0_ARVALID;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_AWVALID = grp_map_4_fu_124_m_axi_gmem_0_AWVALID;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_BREADY = grp_map_4_fu_124_m_axi_gmem_0_BREADY;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_RREADY = grp_map_4_fu_124_m_axi_gmem_0_RREADY;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_WVALID = grp_map_4_fu_124_m_axi_gmem_0_WVALID;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln455_fu_148_p2 == 1'd0) & (icmp_ln440_fu_142_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((icmp_ln455_fu_148_p2 == 1'd1) | (icmp_ln440_fu_142_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln455_reg_185 == 1'd1) | (icmp_ln440_reg_181 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3) & (((icmp_ln455_reg_185 == 1'd1) & (icmp_ln440_reg_181 == 1'd1) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return == 1'd1)) | ((icmp_ln440_reg_181 == 1'd0) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_return == 1'd1) & (icmp_ln323_reg_189 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((icmp_ln440_reg_181 == 1'd0) & (grp_map_4_fu_124_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((ap_predicate_op48_call_state3 == 1'b1) & (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op48_call_state3 = ((icmp_ln455_reg_185 == 1'd1) | (icmp_ln440_reg_181 == 1'd0));
end

assign ap_return = 32'd0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start = grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_489_3_fu_136_ap_start_reg;

assign grp_map_4_fu_124_ap_start = grp_map_4_fu_124_ap_start_reg;

assign icmp_ln323_fu_154_p2 = (($signed(Nt_read_reg_169) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln440_fu_142_p2 = ((mmse_init == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln455_fu_148_p2 = (($signed(Nt) < $signed(32'd1)) ? 1'b1 : 1'b0);

endmodule //MHGD_detect_accel
