-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MHGD_detect_accel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_hat : IN STD_LOGIC_VECTOR (63 downto 0);
    Nt : IN STD_LOGIC_VECTOR (31 downto 0);
    Nr : IN STD_LOGIC_VECTOR (31 downto 0);
    mu : IN STD_LOGIC_VECTOR (31 downto 0);
    H : IN STD_LOGIC_VECTOR (63 downto 0);
    y : IN STD_LOGIC_VECTOR (63 downto 0);
    sigma2 : IN STD_LOGIC_VECTOR (31 downto 0);
    mmse_init : IN STD_LOGIC_VECTOR (31 downto 0);
    lr_approx : IN STD_LOGIC_VECTOR (31 downto 0);
    iter : IN STD_LOGIC_VECTOR (31 downto 0);
    v_tb : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of MHGD_detect_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MHGD_detect_accel_MHGD_detect_accel,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.766000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=956,HLS_SYN_LUT=2110,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal iter_read_reg_123 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln449_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln449_reg_128 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln413_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln413_reg_133 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_86_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_reg_137 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_83_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_acc_reg_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln519_fu_113_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln519_reg_148 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal trunc_ln519_1_fu_118_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln519_1_reg_153 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start : STD_LOGIC;
    signal grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_done : STD_LOGIC;
    signal grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_idle : STD_LOGIC;
    signal grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_ready : STD_LOGIC;
    signal grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_86_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln434_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln519_fu_110_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state12_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MHGD_detect_accel_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        iter : IN STD_LOGIC_VECTOR (31 downto 0);
        bitcast_ln519 : IN STD_LOGIC_VECTOR (30 downto 0);
        empty : IN STD_LOGIC_VECTOR (22 downto 0);
        p_acc : IN STD_LOGIC_VECTOR (31 downto 0);
        icmp_ln449 : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component MHGD_detect_accel_fptrunc_64ns_32_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MHGD_detect_accel_dexp_64ns_64ns_64_8_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74 : component MHGD_detect_accel_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start,
        ap_done => grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_done,
        ap_idle => grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_idle,
        ap_ready => grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_ready,
        iter => iter_read_reg_123,
        bitcast_ln519 => trunc_ln519_reg_148,
        empty => trunc_ln519_1_reg_153,
        p_acc => p_acc_reg_142,
        icmp_ln449 => icmp_ln449_reg_128,
        ap_return => grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return);

    fptrunc_64ns_32_2_no_dsp_1_U8 : component MHGD_detect_accel_fptrunc_64ns_32_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_s_reg_137,
        ce => ap_const_logic_1,
        dout => grp_fu_83_p1);

    dexp_64ns_64ns_64_8_full_dsp_1_U9 : component MHGD_detect_accel_dexp_64ns_64ns_64_8_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv64_0,
        din1 => grp_fu_86_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_86_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                and_ln413_reg_133 <= and_ln413_fu_104_p2;
                icmp_ln449_reg_128 <= icmp_ln449_fu_92_p2;
                iter_read_reg_123 <= iter;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                p_acc_reg_142 <= grp_fu_83_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                tmp_s_reg_137 <= grp_fu_86_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                trunc_ln519_1_reg_153 <= trunc_ln519_1_fu_118_p1;
                trunc_ln519_reg_148 <= trunc_ln519_fu_113_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln449_reg_128, and_ln413_fu_104_p2, and_ln413_reg_133, grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return, ap_CS_fsm_state12, ap_block_state12_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (ap_const_lv1_1 = and_ln413_fu_104_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif (((ap_const_lv1_0 = and_ln413_fu_104_p2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_lv1_0 = and_ln413_reg_133) and (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return = ap_const_lv1_1) and (icmp_ln449_reg_128 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    and_ln413_fu_104_p2 <= (icmp_ln449_fu_92_p2 and icmp_ln434_fu_98_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(ap_block_state12_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state12_on_subcall_done)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state12_on_subcall_done_assign_proc : process(and_ln413_reg_133, grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_done)
    begin
                ap_block_state12_on_subcall_done <= ((ap_const_lv1_0 = and_ln413_reg_133) and (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(icmp_ln449_reg_128, and_ln413_reg_133, grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return, ap_CS_fsm_state12, ap_block_state12_on_subcall_done)
    begin
        if (((ap_const_lv1_0 = and_ln413_reg_133) and (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return = ap_const_lv1_1) and (icmp_ln449_reg_128 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(icmp_ln449_reg_128, and_ln413_reg_133, grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return, ap_CS_fsm_state12, ap_block_state12_on_subcall_done)
    begin
        if (((ap_const_lv1_0 = and_ln413_reg_133) and (grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_return = ap_const_lv1_1) and (icmp_ln449_reg_128 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_const_lv32_0;
    bitcast_ln519_fu_110_p1 <= p_acc_reg_142;
    grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start <= grp_MHGD_detect_accel_Pipeline_VITIS_LOOP_480_3_fu_74_ap_start_reg;
    grp_fu_86_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    icmp_ln434_fu_98_p2 <= "1" when (mmse_init = ap_const_lv32_0) else "0";
    icmp_ln449_fu_92_p2 <= "1" when (signed(Nt) > signed(ap_const_lv32_0)) else "0";
    trunc_ln519_1_fu_118_p1 <= bitcast_ln519_fu_110_p1(23 - 1 downto 0);
    trunc_ln519_fu_113_p1 <= bitcast_ln519_fu_110_p1(31 - 1 downto 0);
end behav;
