-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MHGD_detect_accel is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_hat : IN STD_LOGIC_VECTOR (63 downto 0);
    Nt : IN STD_LOGIC_VECTOR (31 downto 0);
    Nr : IN STD_LOGIC_VECTOR (31 downto 0);
    mu : IN STD_LOGIC_VECTOR (31 downto 0);
    H : IN STD_LOGIC_VECTOR (63 downto 0);
    y : IN STD_LOGIC_VECTOR (63 downto 0);
    sigma2 : IN STD_LOGIC_VECTOR (31 downto 0);
    mmse_init : IN STD_LOGIC_VECTOR (31 downto 0);
    lr_approx : IN STD_LOGIC_VECTOR (31 downto 0);
    iter : IN STD_LOGIC_VECTOR (31 downto 0);
    v_tb : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of MHGD_detect_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MHGD_detect_accel_MHGD_detect_accel,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.303000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=119,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal icmp_ln420_fu_76_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln435_fu_70_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln394_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln466_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    and_ln394_fu_82_p2 <= (icmp_ln435_fu_70_p2 and icmp_ln420_fu_76_p2);
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= ap_const_lv32_0;
    icmp_ln420_fu_76_p2 <= "1" when (mmse_init = ap_const_lv32_0) else "0";
    icmp_ln435_fu_70_p2 <= "1" when (signed(Nt) > signed(ap_const_lv32_0)) else "0";
    icmp_ln466_fu_88_p2 <= "1" when (signed(iter) > signed(ap_const_lv32_0)) else "0";
end behav;
