// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MHGD_detect_accel_MHGD_detect_accel,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.303000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=119,HLS_VERSION=2024_2}" *)

module MHGD_detect_accel (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_hat,
        Nt,
        Nr,
        mu,
        H,
        y,
        sigma2,
        mmse_init,
        lr_approx,
        iter,
        v_tb,
        ap_return,
        ap_rst
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x_hat;
input  [31:0] Nt;
input  [31:0] Nr;
input  [31:0] mu;
input  [63:0] H;
input  [63:0] y;
input  [31:0] sigma2;
input  [31:0] mmse_init;
input  [31:0] lr_approx;
input  [31:0] iter;
input  [63:0] v_tb;
output  [31:0] ap_return;
input   ap_rst;

wire   [0:0] icmp_ln420_fu_76_p2;
wire   [0:0] icmp_ln435_fu_70_p2;
wire   [0:0] and_ln394_fu_82_p2;
wire   [0:0] icmp_ln466_fu_88_p2;
wire    ap_ce_reg;

assign and_ln394_fu_82_p2 = (icmp_ln435_fu_70_p2 & icmp_ln420_fu_76_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = 32'd0;

assign icmp_ln420_fu_76_p2 = ((mmse_init == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln435_fu_70_p2 = (($signed(Nt) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln466_fu_88_p2 = (($signed(iter) > $signed(32'd0)) ? 1'b1 : 1'b0);

endmodule //MHGD_detect_accel
