// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MHGD_detect_accel_MHGD_detect_accel_Pipeline_VITIS_LOOP_483_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        iter,
        bitcast_ln524,
        empty,
        p_acc,
        icmp_ln449,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] iter;
input  [30:0] bitcast_ln524;
input  [22:0] empty;
input  [31:0] p_acc;
input  [0:0] icmp_ln449;
output  [0:0] ap_return;

reg ap_idle;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln524_1_fu_167_p2;
reg   [0:0] icmp_ln483_reg_194;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] merge_reg_94;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln483_fu_124_p2;
wire   [30:0] add_ln483_fu_130_p2;
reg   [30:0] add_ln483_reg_198;
wire   [0:0] icmp_ln524_fu_146_p2;
reg   [0:0] icmp_ln524_reg_203;
wire   [0:0] icmp_ln524_1_fu_152_p2;
reg   [0:0] icmp_ln524_1_reg_208;
reg   [0:0] ap_phi_mux_merge_phi_fu_98_p4;
reg   [30:0] k_fu_60;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_k_load;
wire   [31:0] zext_ln483_fu_120_p1;
wire   [7:0] tmp_fu_136_p4;
wire   [0:0] grp_fu_106_p2;
wire   [0:0] and_ln524_fu_162_p2;
wire   [0:0] or_ln524_fu_158_p2;
reg   [0:0] ap_return_preg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 k_fu_60 = 31'd0;
#0 ap_return_preg = 1'd0;
#0 ap_done_reg = 1'b0;
end

MHGD_detect_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_acc),
    .din1(32'd1056055654),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_106_p2)
);

MHGD_detect_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_preg <= ap_phi_mux_merge_phi_fu_98_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        k_fu_60 <= 31'd0;
    end else if (((1'd0 == and_ln524_1_fu_167_p2) & (icmp_ln483_reg_194 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_fu_60 <= add_ln483_reg_198;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln483_reg_194 == 1'd1) & (1'd1 == and_ln524_1_fu_167_p2) & (1'b1 == ap_CS_fsm_state2))) begin
        merge_reg_94 <= 1'd0;
    end else if (((icmp_ln483_fu_124_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        merge_reg_94 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln483_reg_198 <= add_ln483_fu_130_p2;
        icmp_ln483_reg_194 <= icmp_ln483_fu_124_p2;
        icmp_ln524_1_reg_208 <= icmp_ln524_1_fu_152_p2;
        icmp_ln524_reg_203 <= icmp_ln524_fu_146_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln483_reg_194 == 1'd0) | (1'd1 == and_ln524_1_fu_167_p2)))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln483_reg_194 == 1'd1) & (1'd1 == and_ln524_1_fu_167_p2) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_merge_phi_fu_98_p4 = 1'd0;
    end else begin
        ap_phi_mux_merge_phi_fu_98_p4 = merge_reg_94;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return = ap_phi_mux_merge_phi_fu_98_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_k_load = 31'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_60;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln483_fu_130_p2 = (ap_sig_allocacmp_k_load + 31'd1);

assign and_ln524_1_fu_167_p2 = (or_ln524_fu_158_p2 & and_ln524_fu_162_p2);

assign and_ln524_fu_162_p2 = (icmp_ln449 & grp_fu_106_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign icmp_ln483_fu_124_p2 = (($signed(zext_ln483_fu_120_p1) < $signed(iter)) ? 1'b1 : 1'b0);

assign icmp_ln524_1_fu_152_p2 = ((empty == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln524_fu_146_p2 = ((tmp_fu_136_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln524_fu_158_p2 = (icmp_ln524_reg_203 | icmp_ln524_1_reg_208);

assign tmp_fu_136_p4 = {{bitcast_ln524[30:23]}};

assign zext_ln483_fu_120_p1 = ap_sig_allocacmp_k_load;

endmodule //MHGD_detect_accel_MHGD_detect_accel_Pipeline_VITIS_LOOP_483_3
